title: Sanvi Kaushik
description: 3rd year Software Engineering @ Carleton
theme: jekyll-theme-cayman  

author: Sanvi Kaushik
resume_url: /assets/resume_2025.pdf
github_url: https://github.com/sanvikaushik
linkedin_url: https://www.linkedin.com/in/sanvi-705v1/

plugins: []
